config/routes.rb
Rails.application.routes.draw do
    resources :users, :follows

    get "createuser", to: "users#create"

    root to: "users#index"

end

app/models/follow.rb
class Follow < ActiveRecord::Base
	belongs_to :user
	belongs_to :following, :class_name => "User"
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true

	has_many :follows
	has_many :followings, :through => :follows

    has_many :inverse_follows, :class_name => "Follow", :foreign_key => "following_id"
    has_many :inverse_following, :through => :inverse_follows, :source => :user


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
	def create
		@follower = User.find(params[:user_id])
		@follow = @follower.follows.build(:following_id => params[:follow_id])
		if @follow.save
			flash[:notice] = "Followed user."
			redirect_to @follower
		else
			flash[:error] = "Could not follow user."
			redirect_to root_url			
		end
	end
	def destroy

		@follower = User.find(params[:user_id])

		@follow = @follower.follows.find(params[:follow_id])
		@follow.destroy

		flash[:notice] = "Stopped following user."
		redirect_to @follower
		
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@users = User.all
	end

	def create
		if params[:user]
			@user = User.new(params.require(:user).permit(:name))
			if @user.save
		 		flash[:notice] = "Created user."
		 		redirect_to root_url
			 else
				flash[:error] = "Could not create user."
			 	redirect_to root_url
			 end
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Followme</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <% flash.each do |k, v| %>
   <div class="flash <%= k %>"><%= v %></div>
 <% end %>


<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<%= form_for :user do |f| %>
	<p>
		<%= f.label :name %> <br>
		<%= f.text_field :name %> <br>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/users/index.html.erb
<h1>AppDynamics Users</h1>
<ul>
	<% @users.each do |user| %>
	<li><%= link_to user.name, user %> </li>
	<% end %>
</ul>
<p><%= link_to("Create New User","/createuser") %></p>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Profile</h1>

<h2><%= @user.name %> is Following:</h2>
	<% for follow in @user.follows %>
	<li>
		<%= follow.following.name %> (<%= link_to "remove", follow_path(:follow_id => follow, :user_id => @user), :method =>:delete %>)
	</li>
	<% end %>

<h2><%= @user.name %> is NOT Following:</h2>

	<% @users.each do |otheruser| %>

	<% if not @user.follows.find_by(following_id: otheruser) %>
	<% if @user != otheruser %>
	<li>

		<%= otheruser.name %> (<%= link_to "follow", follows_path(:follow_id => otheruser, :user_id => @user), :method => :post %>)
	</li>
	<% end %>
	<% end %>
	<% end %>

<h2>People Following <%= @user.name %>:</h2>
	<% for follower in @user.inverse_following %>
	<li>
		<%= follower.name %>

	<% if not @user.follows.find_by(following_id: follower) %>

		 (<%= link_to "follow", follows_path(:follow_id => follower, :user_id => @user), :method => :post %>)

	<% end %>

	</li>
	<% end %>


<hr>
<p><%= link_to("Home", root_url) %></p>